/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.tkmtmkt;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import java.io.IOException;
import java.util.List;

public class App {
    public ExprParser getParser(String param) {
//        new org.antlr.runtime.ANTLRFileStream()
        ExprLexer lexer = new ExprLexer(CharStreams.fromString(param));
        CommonTokenStream stream = new CommonTokenStream(lexer);
        ExprParser parser = new ExprParser(stream);

        return parser;
    }

    public void walk(ExprParser.ExprContext expr) {
        ParseTreeWalker walker = new ParseTreeWalker();
        walker.walk(new ExprBaseListener(), expr);
    }

    public static void main(String[] args) {
        App app = new App();
        ExprParser parser = app.getParser("3+4*5");
        ExprParser.ExprContext expr = parser.expr();

        System.out.println("toInfoString : " + expr.toInfoString(parser));
        System.out.println("toString     : " + expr.toString());
        System.out.println("toStringTree : " + expr.toStringTree());
        System.out.println("\n");

        List<ExprParser.TermContext> term = expr.term();
        System.out.println(term.get(0).factor(0).INT());

        app.walk(expr);
    }
}
